# Generated by Django 4.1.4 on 2022-12-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolDemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('size', models.IntegerField(default=0, verbose_name='size')),
                ('od_date', models.DateTimeField(default=None, verbose_name='od date')),
            ],
        ),
    ]
