# Generated by Django 4.1.4 on 2022-12-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooldemomodel',
            name='remark',
            field=models.CharField(default='', max_length=100, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='pooldemomodel',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
    ]
