# Generated by Django 4.1.4 on 2022-12-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_alter_pooldemomodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooldemomodel',
            name='db_type',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
    ]
